### ISSUE TITLE
2015 Js series

### ISSUE THREAD

**Issue by rome1983** [roberodin/ha-samsungtv-custom#12]
Can you add the encrypted method for 2015 js series?

**Comment by jjwBullfrog** [comment]
Same request here. I have UNJS8000. Thank you in advance!!

**Comment by jaedeezy** [comment]
Any luck getting this component set up? JS8500 here and can't get any controls working

**Comment by jjwBullfrog** [comment]
No luck at all. Let me know if you find something.

**Comment by rome1983** [comment]
I will try this out 
https://github.com/smartHomeHub/SmartIR

**Comment by leonardpitzu** [comment]
for older samsung tv's this does cover the encryption part: https://github.com/eclair4151/SmartCrypto
would be great if you could integrate these older tv's

**Comment by rome1983** [comment]
Seems to be no interest in any one writing a proper home assistant integration. I’m currently happy with my method above and using the Samsung integration for on/off state.

**Comment by firstof9** [comment]
Seems the way to control TVs like the UN50J5200 is via UPnP
