### ISSUE TITLE
I wanted to say good job

### ISSUE THREAD

**Issue by kdschlosser** [roberodin/ha-samsungtv-custom#14]
Nice work so far, 

Sorry for not completing the library. I never managed to get access to one to be able to complete the thing. It would have probably only taken me a few hours to sort out the last of the bugs. No one I know owns a Samsung TV and I wasn't going to go out and buy one. It looks as tho you are using several libraries in order to get some kind of a working scenario.

The library I wrote is written to work with 2011 and newer TV's It just needs to have some issues with the power on the newer TV's sorted out and also with the automatic detection. I did want to let you know that there is a bunch of really cool functionality built into the UPNP side of things, and that the older the TV the better the UPNP is. 

I would like you to do me a favor if you don't mind.

Can you please copy the LICENSE file from my repo and either paste it onto the end of you LICENSE file or create a LICENSE file in the samsnugctl portion of your program. I am only asking this because my work is a fork of another repo. Tho there is not much original code left It is still important to make sure the license information is passed along... The Apache 2 license and the MIT license work together without issue. there is but a single requirement that the MIT license be included under the Apache 2 license. I want to make sure that you are in good standing for using the code and that anyone that has worked on the project before me can't grumble and complain at ya..

**Comment by roberodin** [comment]
Hello, now you are a collaborator of the project, change what you want.

Sorry, right now I don't have time to look at it myself.

Thank you all.

**Comment by roberodin** [comment]
Hello, now you are a collaborator of the project, change what you want.

Sorry, right now I don't have time to look at it myself.

Thank you all.
