### ISSUE TITLE
TV ask HASS for permission over and over

### ISSUE THREAD

**Issue by frelev** [roberodin/ha-samsungtv-custom#27]
I installed the custom component using HACS but after reboot HASS complained about missing samsungctl so I installed that manually using PIP3. However, since I have a QLED (The Frame) I also installed the custom component for it: https://github.com/giefca/ha-samsungtv-qled/tree/master/custom_components/samsungtv_qled

The custom component seems to work for changing apps (Netflix, Plex etc) but my issue is that for on/off, volume etc the TV ask for permission approval for HASS every time and therefore nothing happens.

Anyone knows how to fix this?

```
  - platform: samsungtv_custom
    host: 192.168.1.XXX
    port: 8002
    mac: d0:d0:XX:XX:XX
    name: The Frame
    applist: "YouTube, Plex, Netflix, Spotify"
    protocol: ctl_qled

```

**Comment by frelev** [comment]
setting timeout seems to solve it

**Comment by adriaanh** [comment]
Can you elaborate on where you changed the timeout setting?

**Comment by adriaanh** [comment]
Sorry, found it already in #10

**Comment by docbobo** [comment]
For me, timeout isn't fixing it either. I also followed all the instructions described in #10 - without success. 
BTW, the Home Assistant Samsung component doesn't seem to document "timeout" anymore. Is this related?
