### ISSUE TITLE
TV does not respond to commands

### ISSUE THREAD

**Issue by DanskerUS** [roberodin/ha-samsungtv-custom#3]
The TV does not respond to any commands (except .turn_on).

This is identical to the plain samsungtv integration.

It DOES show on/off status.

**Comment by dolenec** [comment]
Which TV model do you have?

What is your code in config? Because I do not get any status..

**Comment by DanskerUS** [comment]
Samsung   UN32N5300AFXCA
Samsung UN43RU7100F

**Comment by DanskerUS** [comment]
Updated to latest version, same problem.

**Comment by guiwood** [comment]
Same problem here. It is the same in the native samsungtv integration. Interesting that i have been using homebridge as well, and samsung tv integration works in homebridge, with keys support.

**Comment by roberodin** [comment]
Hi, I have uploaded the latest version 2.0. Try changing the protocol to "ws" for 2016+ TVs model! (maybe all tizen family)...

- platform: samsungtv_custom
host: xxx.xxx.xxx.xxx
sourcelist: '{"PlayStation": "KEY_HDMI1", "RaspberryPi": "KEY_HDMI2", "Chromecast": "KEY_HDMI3"}'
port: (8001 or 8002)
mac: xx:xx:xx:xx:xx
**protocol: ws**

**Comment by roberodin** [comment]
Update to version 3.0.0 and try the new protocols:
-ws (fixed from @xchwarze)
-ctl_beta (is the same as samsungtv_2.zip)
-ctl_qled
