### ISSUE TITLE
Travis Failing on Websocket error

### ISSUE THREAD

**Issue by Chaotic** [roberodin/ha-samsungtv-custom#33]
I'm getting this error when checking my config via Travis
`Failed config
  General Errors: 
    - Platform error media_player.samsungtv_custom - No module named 'websocket'`

Here is my config for this module
`platform: samsungtv_custom
host: !secret living_room_tv_ip
mac: !secret living_room_tv_mac
name: "Samsung Living Room TV"
port: 8002
protocol: ws
sourcelist: '{"Chromecast": "KEY_HDMI1", "Switch": "KEY_HDMI2"}'`

and my travis code

`language: python
python:
  - "3.7"
before_install:
  - mv not_secrets.yaml config/secrets.yaml
  - sudo apt-get install -y libudev-dev
install:
  - pip3 install homeassistant
script:
  - hass -c ./config/ --script check_config`

The actual code works fine in my docker install but I'd really like to get this issue fixed if possible.

**Comment by terminet85** [comment]
pip3 install websocket-client==0.56.0

**Comment by Chaotic** [comment]
that fixed it thanks
