### ISSUE TITLE
New ideas

### ISSUE THREAD

**Issue by escoand** [roberodin/ha-samsungtv-custom#4]
Hi @roberodin.

I would be interested in working together with you to get this integration to another level. I've already started multiple attempts ([the last](https://github.com/home-assistant/home-assistant/pull/26865)) to do this but get stuck by the not supported samsungctl library. For me it seems to be the game changer to get the [fork from kdschlosser](https://github.com/kdschlosser/samsungctl) to PyPi. When somebody is willing to do this we have done a big step further.

Additionally for my old TV UE40ES5700 (legacy protocol) the connection is very limited as it is only an smart IR remote. You are only able to send key codes but not more. Don't know what with the websocket protocol is doable.
Therefore I [investigated](https://github.com/escoand/home-assistant/tree/samsungtv_upnp/homeassistant/components/samsungtv_upnp) the also existing UPNP interface. With this I was able to get much more power than the current samsungctl could give.

I'm now somehow familiar with all the config_flow thing and could implement this if you're interested. Also I could extend here and there in your custom component as I did this in my attempts as well.

What do you thing to all this?

**Comment by 1DontEx1st** [comment]
Just curious - have you considered having these changes implemented in the official component?

**Comment by escoand** [comment]
Not yet, I tried as you can see in the link above. But I need to split it in smaller ones. But one time you always come to the point that we need the newer fork from kdschlosser which is not at PyPi.

**Comment by dolenec** [comment]
Maybe to add HTTP post commands for opening applications:
https://www.panbachi.de/samsung-tv-app-starten-ueber-http/

For me this is working (using YouTube and Netflix).

**Comment by escoand** [comment]
@dolenec It's not desired to have protocol specific things in the integrations. That was also a point why my upnp integration was denied.

**Comment by roberodin** [comment]
I am quite disappointed with Samsung TVs specifically with the tizenOS operating system, the best solution to all this is to buy something with Android TV!

**Comment by roberodin** [comment]
@escoand I added several protocols or versions to the component to cover more models, if you want to add some more do a PR and package it all

**Comment by escoand** [comment]
@roberodin what do you think about upstreaming your work?
