### ISSUE TITLE
HACS problem

### ISSUE THREAD

**Issue by andlill** [roberodin/ha-samsungtv-custom#6]
Hi, I get the following in Hacs

"Unsupported Home Assistant version
You have version '0.99.2' of Home Assistant, but version '1.0.1' of 'SamsungTV Custom' require version 'None' of Home Assistant, installation and upgrades are disabled for this integration untill you upgrade Home Assistant."

Any tips ?

**Comment by dolenec** [comment]
Do you have same problem wizh 0.100.2 HA version?

**Comment by roberodin** [comment]
The component is designed for minimum 0.99.3
