### ISSUE TITLE
Does not work for my TV UE55MU7072

### ISSUE THREAD

**Issue by LordBoos** [roberodin/ha-samsungtv-custom#7]
This unfortunately does not work for my TV at all. It only turns on, but then nothing can be controlled and state is not updated - still shows the TV as OFF.
My configuration:
```
  - platform: samsungtv_custom
    name: samsung tv custom test
    host: 192.168.0.102
    port: 8002
    mac: !secret samsung_tv_mac
    sourcelist: '{"Xiaomi Mi Box": "KEY_HDMI1", "HDMI2": "KEY_HDMI2", "HDMI3": "KEY_HDMI3"}'
    protocol: ws
```
However I have custom version of samsungtv component that I've glued together from multiple revisions of different fixes and workarounds I've found on the web and this works perfectly fine for my TV, but it doesn't have source selection (only TV/HDMI but I cannot switch to HDMI2 or 3 or rename them). I think that it might help you to fix this component, so here it is:
[samsungtv_2.zip](https://github.com/roberodin/ha-samsungtv-custom/files/3739471/samsungtv_2.zip)
And it's working configuration for my TV:
```
  - platform: samsungtv_2
    host: 192.168.0.102
    port: 8002
    timeout: 5
    mac: !secret samsung_tv_mac
```

**Comment by Raoulex** [comment]
@LordBoos just edit from the folder the media_player.py and edit the source section, just add the keys for other inputs

![image](https://user-images.githubusercontent.com/47702014/67030586-622aec00-f118-11e9-9e60-260111da607e.png)

**Comment by dolenec** [comment]
Great info, so probably we can wait so that component will be merged and updated..

**Comment by dolenec** [comment]
Probably also this would be great to be merged:
https://github.com/giefca/ha-samsungtv-qled

**Comment by roberodin** [comment]
> This unfortunately does not work for my TV at all. It only turns on, but then nothing can be controlled and state is not updated - still shows the TV as OFF.
> My configuration:
> 
> ```
>   - platform: samsungtv_custom
>     name: samsung tv custom test
>     host: 192.168.0.102
>     port: 8002
>     mac: !secret samsung_tv_mac
>     sourcelist: '{"Xiaomi Mi Box": "KEY_HDMI1", "HDMI2": "KEY_HDMI2", "HDMI3": "KEY_HDMI3"}'
>     protocol: ws
> ```
> 
> However I have custom version of samsungtv component that I've glued together from multiple revisions of different fixes and workarounds I've found on the web and this works perfectly fine for my TV, but it doesn't have source selection (only TV/HDMI but I cannot switch to HDMI2 or 3 or rename them). I think that it might help you to fix this component, so here it is:
> [samsungtv_2.zip](https://github.com/roberodin/ha-samsungtv-custom/files/3739471/samsungtv_2.zip)
> And it's working configuration for my TV:
> 
> ```
>   - platform: samsungtv_2
>     host: 192.168.0.102
>     port: 8002
>     timeout: 5
>     mac: !secret samsung_tv_mac
> ```

I'm going to test it

**Comment by roberodin** [comment]
Update to version 3.0.0 and try the new protocols:
-ws (fixed from @xchwarze)
-ctl_beta (is the same as samsungtv_2.zip)
-ctl_qled

**Comment by roberodin** [comment]
> Probably also this would be great to be merged:
> https://github.com/giefca/ha-samsungtv-qled

Merged!
